name: "Dimension Media"
description: "Film Productions"

url: "http://localhost:4000"
# url: "http://dimension-media.github.com" 

paginate: 10

markdown: redcarpet
permalink: /:year/:month/:day/:title
pygments: true



